<section>
        <h1><?php echo $judul ?></h1> 
        <p align='justify'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita hic voluptatem ab ipsum dolorem at, minus repudiandae mollitia recusandae consequuntur maxime nobis? Enim iure laudantium commodi hic animi quaerat fugit?</p> 
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi provident dolores consequatur vel enim, placeat modi earum. Odio ipsum saepe, unde laudantium officia qui autem error id quo, a dignissimos?.</p>        
            <ol type="a"> 
            <li>Model</li> 
        <p align='justify'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga, esse sit! Reprehenderit hic labore fuga? Repudiandae iste magnam ex animi facere voluptatem, commodi reiciendis suscipit nulla provident, est labore illo?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum temporibus facere, laudantium aut labore, praesentium qui ducimus quia molestiae perspiciatis repellat. Numquam tempora fugiat laudantium modi voluptatem facere similique sapiente.</p> 
        <p align='justify'>Sebagai catatan, Semua model harus disimpan di 
        dalam folder application\models</p> 
            <li>View</li> 
        <p align='justify'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sint voluptas accusantium adipisci repellat hic animi iste impedit, nam quod accusamus odit doloremque ducimus consectetur culpa. A sit placeat voluptatum est. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil nostrum neque debitis cum sint et fugit laborum, quo libero delectus. Sit illum perspiciatis aut, velit officia omnis earum odio vel.</p> 
            <li>Controller</li> 
        <p align='justify'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore maxime itaque numquam ea veritatis, culpa alias ad qui dicta sit voluptate aliquam odio incidunt est natus amet corporis animi libero. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum a illo laboriosam rerum aperiam quae. Quibusdam tempore exercitationem voluptate possimus recusandae sint obcaecati, rerum quis maiores optio, impedit laudantium minus?</p> 
        <p align='justify'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ratione sed unde enim, repellat veniam culpa vitae assumenda aspernatur fugit officia quo, ea delectus amet architecto ipsum! Iste maiores eius placeat. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sint ratione nesciunt ullam. Impedit voluptatum debitis, molestias consequuntur expedita, rerum consectetur quasi quibusdam minus soluta odit, rem veritatis laudantium sit non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore consectetur veniam, error tempore eaque dolorem, tempora esse illum temporibus libero modi distinctio! Odio quia reprehenderit omnis optio est enim eos.</p> 
</section> 